FROM ghcr.io/gbraad-devenv/opensuse/base:15.5

USER gbraad

RUN git clone https://github.com/gbraad/dotfiles ~/.dotfiles \
    && rm -f ~/.zshrc \
    && ~/.dotfiles/install.sh

ENTRYPOINT [ "/bin/zsh" ]